server:
  port: 9000
proxy:
  apis:
    - name: 後端服務1
      path: proxy1
      url: http://localhost:9091
    - name: 後端服務2
      path: proxy2
      url: http://localhost:9091
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    config-url: /proxy/swagger-config